url: 'https://oringa.github.io/' # your main domain
baseurl: 'AEAI/' # if you're using custom domain keep this blank example: baseurl: ''

theme: jekyll-theme-cayman
# github:
#   is_project_page: false

author :
  name : Alon Oring